name: Dependency Submission
on:
  push:
    branches:
      - main

# The API requires write permission on the repository to submit dependencies
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 23
        architecture: x64
    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v3
       
